server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: vitality
  datasource:
    url: jdbc:postgresql://localhost:5432/vitality
    username: vitality
    password: ${DB_PASSWORD:vitality1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:YjN8eHcyaDhrdTVlN2tqZnQ4bHkzcDZlNHg1dTluOHIydTBlcjR3OWowbTF0djlhM2U3b3NwNmVlMjRtOA==}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
  google:
    client-id: ${GOOGLE_CLIENT_ID:698316200364-tl3t0nd32e949v2fp9lfullrfpc9p443.apps.googleusercontent.com}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost}

logging:
  level:
    com.vitality: DEBUG
    org.springframework.security: INFO
